//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcunMedyaPortfolioProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialMedia
    {
        public int id { get; set; }
        public string platform_Name { get; set; }
        public string platform_URL { get; set; }
        public string platform_username { get; set; }
        public string image_url { get; set; }
    }
}
